### ISSUE TITLE
Cut new release and deploy to PyPI/conda-forge

### ISSUE THREAD

**Issue by imagejan** [mobie/mobie-utils-python#133]
Hi @constantinpape,

I noticed the latest tag https://github.com/mobie/mobie-utils-python/releases/tag/0.4.5 is from April 2023. Do you plan to cut a release anytime soon? 🙂

**Comment by martinschorb** [comment]
I guess now would be ideal. We bumped the version already after switching the default file format to OME-Zarr.

**Comment by constantinpape** [comment]
Yes, good point. I forgot to cut the actual release after bumping the version.

**Comment by constantinpape** [comment]
New release is done. Should be on conda-forge soon.

**Comment by martinschorb** [comment]
Hi, 
there was a discrepancy in version numbering. Could you deploy it again? Now everything should be in sync.

**Comment by constantinpape** [comment]
I decided to rather make another patch release (with corrected updated version string).
I think #134 is quite important, since without it using this package on windows is quite impaired, so it's good to release this right away.

I will wait for the auto release of conda-forge for this one (since we don't need any other version pins), but it should be there at some time tomorrow.
