### ISSUE TITLE
Importer produced empty N5 data 

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#22]
Hi,

I ran the workflow as in the example:

```
mobie.initialize_dataset(data_path, data_key,
    ...:                          mobie_root, dataset_name, data_name,
    ...:                          resolution, chunks, scale_factors,
    ...:                          target='slurm',max_jobs=240)

```
with arguments 
```
./AMST_cropped/
 - *.tif
 - ./mobie
 - FIB-SEM
 - raw-data
```

in directory `/g/emcf/ronchi/Gross-Irene-Periacqueductal gray#2910/Gross-Irene_F056_20-11-02_Sam/processing/`

all went fine without any errors ( it did not create the "data" subdirectory that MoBIE is looking for), just the data is completely empty...

**Comment by constantinpape** [comment]
The time limit for the copy jobs were exceeded, see `/g/emcf/ronchi/Gross-Irene-Periacqueductal gray#2910/Gross-Irene_F056_20-11-02_Sam/processing/tmp_FIB-SEM/error_logs/copy_volume_initial_scale_0.err`.
Somehow the error was not properly caught and then processing continued.

The underlying issue is that reading from these tif stacks while rechunking  is still very inefficient; I am not so sure why because it uses memmap internally; but it seems that's not as efficient as I thought. Also, performance will probably suffer more when you are using so many workers because they are all accessing the same tif file.

I am running the conversion on one of our larger machines right now, I can let you know when it's done and you could just copy the data to the right location.

**Comment by martinschorb** [comment]
It then might make sense to come up with recommendations on the ideal number of workers given a certain dataset size.

Also, perhaps the chunking operation could be distributed such that there are no/minimal concurrent reads on the same slice.
In general, I find it very hard to come up with good values for distributing the workers. Right now I am struggling with using dask on very similar tasks. There seems to be a fine line of when massive parallelization actually provides benefits versus the additional overhead caused by distributing data.

**Comment by constantinpape** [comment]
> It then might make sense to come up with recommendations on the ideal number of workers given a certain dataset size.

At least here, this is only such an issue issue due to tif input data. If the input data was chunked it would be much less of an issue.

> Also, perhaps the chunking operation could be distributed such that there are no/minimal concurrent reads on the same slice.

Yes, there is probably a slightly better strategy to do this here, by loading `CHUNK_SIZE_Z` image planes with a single worker and then writing out all corresponding chunks.
(This comes with some other problems though, because it will be inefficient for very large image sizes).
I think an even better strategy would be if you can write the input data in a chunked format directly, there might be some pre-processing step that loads all data into RAM anyways (AMST?), so writing the result chunked would come at almost zero cost.

> In general, I find it very hard to come up with good values for distributing the workers. Right now I am struggling with using dask on very similar tasks. There seems to be a fine line of when massive parallelization actually provides benefits versus the additional overhead caused by distributing data.

Yes, this is one of the fundamental trade-offs in distributed computing and unfortunately there is no one fits all solution.

**Comment by constantinpape** [comment]
@martinschorb the converted data is here: `/scratch/pape/mobie-test/peria-test/test/images/local/raw.n5`

**Comment by constantinpape** [comment]
@martinschorb do you still need the data @ `/scratch/pape/mobie-test/peria-test/test/images/local/raw.n5`?
I am close to reaching my scratch quota, so would be good to remove it when possible.

**Comment by martinschorb** [comment]
Don't worry it's copied.
