### ISSUE TITLE
spec-v2 new source names for crop 

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#31]
Hi,

it seems the validation of source names fails when the source name is defined in a  later transform field.
We had this problem once before, I think...

```
Traceback (most recent call last):
  File "centriole_analysis.py", line 348, in <module>
    cview = mm.get_view(names = [centname],
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/metadata/view_metadata.py", line 258, in get_view
    assert len(set(_sources) - set(source_list)) == 0
AssertionError
```

**Comment by constantinpape** [comment]
I thought I had fixed this, but maybe I overlooked something. Can you point me to the code that throws this error?

**Comment by constantinpape** [comment]
I had a look at this and I updated some tests and they work as expected, see https://github.com/mobie/mobie-utils-python/blob/spec-v-02/test/metadata/test_view_metadata.py#L291-L301. 

So I think the issue is in your code; probably you are giving an incorrect name in `get_image_display` (https://github.com/mobie/centrioles-tomo-datasets/blob/main/centriole_analysis.py#L340 but that's probably not quite up-to-date with the code that you are using).

I have also updated the error message, so if you pull in mobie-utils the error should become clear.

**Comment by martinschorb** [comment]
> So I think the issue is in your code; probably you are giving an incorrect name in `get_image_display` (https://github.com/mobie/centrioles-tomo-datasets/blob/main/centriole_analysis.py#L340 but that's probably not quite up-to-date with the code that you are using).

True, I also had to update this call.
