### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#46]
Hi,

I just stumbled 😕 when installing the package in a fresh Conda environment and noticed:

- the repo is called `mobie-utils-python`
- the conda package is called `mobie_utils`
- the python package is called `mobie`

Could we make that more consistent?

**Comment by constantinpape** [comment]
Changing the python or repo name would be quite a lot of work.
Changing the repo-name would be easy, but I actually think that having "python" in the repo name is helpful.
In general, this is what documentation is for: https://github.com/mobie/mobie-utils-python#installation

**Comment by martinschorb** [comment]
I understand the potential complications, nevertheless the situation got me confused and it took me ~1.5 minutes to realize why.
Having the conda and python package name consistent (as most packages without a `-` do) would make checking the documentation before each installation unnecessary.

**Comment by constantinpape** [comment]
I won't change the python name, a lot of code I have depends on this and this would be an absolutely undue effort to change it for some minor convenience.
Changing the conda name:
- I don't know if that's even possible (it might cause issues with the conda-forge infrastructure)
- I don't think that `mobie` is  a good conda name, since it could imply that this installs the actual mobie (since conda is not an exclusive pytohn packaging system)

**Comment by martinschorb** [comment]
Makes sense.
Let's see if others have the same issue. And an extra minute for checking documentation before installing it should be feasible.
