### ISSUE TITLE
Deploy python package to pypi

### ISSUE THREAD

**Issue by haesleinhuepf** [mobie/mobie-utils-python#71]
Hi @constantinpape ,

awesome to see python support for mobie. Just a quick question: Do you think it would be possible to ship this as proper python package via pypi? You know, it would allow easy installation, also of former versions, improve reproducible science, etc...

I guess you know already, you only need an account on [pypi.org][(https://pypi.org/) and execute [these four lines](https://github.com/haesleinhuepf/the-segmentation-game/blob/main/deploy.bat) from the root folder of your repository to deploy to pypi. 

Let me know if I can help!

Best,
Robert

**Comment by constantinpape** [comment]
Hi @haesleinhuepf, unfortunately it's not possible to put the library on pypi, because it needs several dependencies that are only available via conda and will be very hard to deliver via pypi (because they are c++ libraries wrapped to python and building them as wheels is very challenging).

> You know, it would allow easy installation, also of former versions, improve reproducible science, etc...

It's available via conda-forge, which is superior to pypi in many of these respects ;) (except easy installation I guess, but reproducibility and versioning is much better....)

> Let me know if I can help!

Unless you have >~ 2 months of a dev ops person I fear there is not much that can be done about this; I looked into this quite a bit already and providing the dependencies as pip packages in a sustainable effort would be a major effort.

**Comment by constantinpape** [comment]
For reference: here is a forum post with some background on this: https://forum.image.sc/t/publish-napari-plugin-with-conda-dependencies/65653

**Comment by constantinpape** [comment]
> > 
> 
> Ah cool, that means `mobie` could be available via conda? That would be cool as well!

The python library is available via conda already, see the installation instructions and `conda install -c conda-forge mobie_utils` should work (if not let me know; this is an issue I would def. want to fix).
See https://github.com/mobie/mobie-utils-python#installation for details.

And also to clarify things a bit: the python library is only for creating and modifying mobie projects; the mobie viewer is then installed via fiji, see https://mobie.github.io/ for details. (And it also comes with a user-friendly GUI for creating MoBIE projects; but it is not quite as flexible and doesn't deal with big data as good as the python library.)

**Comment by constantinpape** [comment]
Oh, and one final caveat: it's not well tested on windows and there might be some issues if you use windows style paths (i.e. using something like `C:\users\haase\...` instead of `c/users/haase/...`). I could look into fixing this in the long term, but would need someone to help a bit because I have not much experience with windows...

**Comment by haesleinhuepf** [comment]
Ah now I see! I just read `pip install -e .` in the instructions. But if it's on conda, it's all good. Thanks for the clarification @constantinpape and have a great weekend ! 🙌

**Comment by constantinpape** [comment]
> Ah now I see! I just read `pip install -e .` in the instructions.

Ok :). (Yeah, that's just the part about setting it up in development mode)
